### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by martab0** [asiakostrzewa/markdown_introduction#1]
Świetnie! Jest wszystko co było na zajęciach plus trochę więcej :-)

Co warto sprawdzić:
- tytuł można by usunąć ze spisu treści,
- blok kodu pojawia się dwa razy,
- odsyłacz https://www.markdownguide.org/cheat-sheet/ prowadzi do innego adresu.

Co można wypróbować (spoza programu zajęć):
- wzory matematyczne - inny sposób dla odróżnienia od kodu,
- wyrównanie tekstu w tabeli do prawej, do lewej, centralnie,
- odsyłacz z jednego pliku do innego.

**Comment by asiakostrzewa** [comment]
Dziękuję za przegląd zadania i informację zwrotną :)
Zaktualizowałam zadanie o następujące funkcje:

- dodałam dwa przykłady przedstawiania wzorów matematycznych. Niestety nie wiem dlaczego w VSC wyświetlają się one poprawnie na podglądzie, a w GitHub Pages jako kod :( 
- dodałam wyrównanie tekstu w tabeli do prawej, do lewej, centralnie. Muszę jednak pokombinować jeszcze, żeby nagłówki tabeli się nie wyrównywały w taki sam sposób, jak testy zawarte wewnątrz tabeli...
- odsyłacz z jednego pliku do innego postanowiłam odpuścić w tym projekcie, ponieważ chciałam zachować styl Quide'a jako one pager'a;
- tytuł "Quick Markdown Guide" wykluczyłam ze spisu treści, ale zostawiłam tam "This is Title", ponieważ moim zamysłem było przedstawienie funkcji nagłówka stopnia pierwszego; 
- zostawiłam też obydwa bloki kodu, ponieważ pierwszy z nich został utworzony przy użyciu funkcji ">", natomiast drugi z nich przygotowałam stosując symbol "```"
- nie rozumiem dlaczego drugi przykład linku nie prowadzi do właściwego miejsca... zastosowałam składnię, którą testowaliśmy podczas zajęć: 
nawias kwadratowy z nazwą linku + nawias okrągły z linkiem
oraz
nawias kwadratowy z linkiem + pusty nawias okrągły

**Comment by martab0** [comment]
Wzory - dla odróżnienia od kodu - powinny dać się zrobić tak:
```
$$
f(x) = ax + b
$$
```
Efekt powinien wyglądać tak:

$$
f(x) = ax + b
$$

Uwaga: może być potrzebny pusty wiersz między poprzednim zdaniem a $$.

**Comment by martab0** [comment]
Odsyłacz z widocznym adresem trzeba podać tak, żeby adres był i w nawiasie kwadratowym, i okrągłym:
```
[https://www.markdownguide.org/cheat-sheet/](https://www.markdownguide.org/cheat-sheet/)
```

**Comment by martab0** [comment]
> dodałam wyrównanie tekstu w tabeli do prawej, do lewej, centralnie. Muszę jednak pokombinować jeszcze, żeby nagłówki tabeli się nie wyrównywały w taki sam sposób, jak testy zawarte wewnątrz tabeli...

Przyznam, że nie wiem, jak to zrobić (żeby nagłówki wyrównywały się inaczej niż wiersze tabeli :-)

> odsyłacz z jednego pliku do innego postanowiłam odpuścić w tym projekcie, ponieważ chciałam zachować styl Quide'a jako one pager'a;

Rozumiem, ma to sens!

> tytuł "Quick Markdown Guide" wykluczyłam ze spisu treści, ale zostawiłam tam "This is Title", ponieważ moim zamysłem było przedstawienie funkcji nagłówka stopnia pierwszego;

W takim przypadku można równie dobrze zostawić oryginalny tytuł w spisie treści, nie jest to błędem.

> zostawiłam też obydwa bloki kodu, ponieważ pierwszy z nich został utworzony przy użyciu funkcji ">", natomiast drugi z nich przygotowałam stosując symbol "```"

Rozumiem. Zwykle "```" używa się do bloków kodu, ">" do cytatów, a "$$" do wzorów (o ile działa poprawnie).

**Comment by asiakostrzewa** [comment]
Dziękuję za pomoc i wszystkie sugestie :)

- Poprawiłam odsyłacze - teraz obydwa działają właściwie;
- Testowałam różne rozwiązania dla wzorów matematycznych, ale wygląda na to, że coś jest nie tak w GitHub Pages:
w [repozytorium](https://github.com/asiakostrzewa/markdown_introduction/blob/main/index.md) wzory wyświetlają się właściwie, ale niestety nie ma to odzwierciedlenia w [GitHub Pages](https://asiakostrzewa.github.io/markdown_introduction/) :(
- Przeszukałam też [forum](https://stackoverflow.com/questions/45680994/left-align-headers-in-markdown-table) pomocy w sprawie wyrównania nagłówków w tabeli i podobno zależy to od implementacji Markdowna w Git'cie. Na pozostałych forach, które odwiedziłam - również nikt nie spotkał się uniezależnieniem wyrównania nagłówka od pozostałej części tabeli,

**Comment by martab0** [comment]
* Odsyłacze już OK :)
* Co do wzorów - tak, podstawowe GitHub Pages ich nie wyświetlają ze znakiem $ (chociaż w repozytorium to działa); dłuższy wątek na ten temat: https://github.com/orgs/community/discussions/22525
* Co do nagłówków w tabeli - tak, sprawdzona metoda pozwala wyrównać nagłówek i zawartość kolumny w ten sam sposób i to działa mniej więcej wszędzie; inne metody zależą od rozszerzenia Markdowna. Czyli jak zwykle z .md - im bardziej ambitne zadanie, tym mniej uniwersalne rozwiązanie :(
